name: Toolbox Builder
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: push Current Project
        run: |
          bash -e ./build.sh
      - name: Upload Armbian image
        uses: actions/upload-artifact@master
        with:
          name: Armbian_firmware
          path: /tmp/output.tar.bz2